
# --- !Ups

create table "person" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "document" varchar not null,
  "name" varchar not null,
  "birthdate" date not null
);

# --- !Downs

drop table "person" if exists;